source_directories:
    - /home


retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6

storage:
  encryption_passphrase: "q1w2e3r4"

repositories:
    - path: ssh://lab2/storage/backups/pc

exclude_patterns:
  - '**/__pycache__'
  - '**/*.pyc'
  - '**/.mypy_cache'
  - '**/.pytest_cache'
  - '**/.tox'
  - '**/dist'
  - '**/build'
  - '**/.eggs'
  - '**/*.egg-info'
  - '**/.coverage'
  - '**/.venv'
  - '**/venv'
  - '**/node_modules'
  - '**/bower_components'
  - '**/jspm_packages'
  - '**/.parcel-cache'
  - '**/bin'
  - '**/obj'
  - '/home/*/.cache'
  - '/home/*/.local'
  - '/home/*/.thumbnails'
  - '/home/*/.gvfs'
  - '/home/*/.npm'
  - '/home/*/.yarn'
  - '/home/*/.cargo'
  - '/home/*/.conda'
  - '/home/*/.rustup'
  - '/home/*/.vscode'
  - '/home/*/thirdparty'
  - '/home/*/Downloads'
  - '/home/*/Pictures'


hooks:
  before_backup:
    - >
      curl -s -X POST "https://api.telegram.org/bot8280614689:AAHLtcLJOhqnbOaw32baZ5-3JgNF2Odm6Lw/sendMessage"
      -d "chat_id=848700511"
      -d "text=Starting backup on $(hostname)..."
  after_backup:
    - >
      curl -s -X POST "https://api.telegram.org/bot8280614689:AAHLtcLJOhqnbOaw32baZ5-3JgNF2Odm6Lw/sendMessage"
      -d "chat_id=848700511"
      -d "text=Backup finished on $(hostname)!"
